"""Production and process-local adapters for frozen repository ports."""

from app.opportunity_intelligence.persistence.memory import (
    DashboardProjectionMemoryRepository,
    DetectionMemoryRepository,
    EvidenceMemoryRepository,
    ExplanationMemoryRepository,
    FeatureSnapshotMemoryRepository,
    InMemoryImmutableRepository,
    LifecycleMemoryRepository,
    MarketContextMemoryRepository,
    MarketSnapshotMemoryRepository,
    NotificationMemoryRepository,
    OpportunityDetailMemoryRepository,
    OpportunityMemoryRepository,
    OpportunityPlanMemoryRepository,
    QualificationMemoryRepository,
    RankingMemoryRepository,
    RuntimeGovernanceMemoryRepository,
    ScoringMemoryRepository,
)
from app.opportunity_intelligence.persistence.postgresql import (
    DashboardProjectionPostgreSQLRepository,
    DetectionPostgreSQLRepository,
    EvidencePostgreSQLRepository,
    ExplanationPostgreSQLRepository,
    FeatureSnapshotPostgreSQLRepository,
    LifecyclePostgreSQLRepository,
    MarketContextPostgreSQLRepository,
    MarketSnapshotPostgreSQLRepository,
    NotificationPostgreSQLRepository,
    OpportunityDetailPostgreSQLRepository,
    OpportunityPlanPostgreSQLRepository,
    OpportunityPostgreSQLRepository,
    PostgreSQLImmutableRepository,
    QualificationPostgreSQLRepository,
    RankingPostgreSQLRepository,
    RuntimeGovernancePostgreSQLRepository,
    ScoringPostgreSQLRepository,
)


__all__ = (
    "DashboardProjectionMemoryRepository",
    "DashboardProjectionPostgreSQLRepository",
    "DetectionPostgreSQLRepository",
    "DetectionMemoryRepository",
    "EvidenceMemoryRepository",
    "EvidencePostgreSQLRepository",
    "ExplanationPostgreSQLRepository",
    "ExplanationMemoryRepository",
    "FeatureSnapshotMemoryRepository",
    "FeatureSnapshotPostgreSQLRepository",
    "LifecyclePostgreSQLRepository",
    "InMemoryImmutableRepository",
    "LifecycleMemoryRepository",
    "MarketContextMemoryRepository",
    "MarketContextPostgreSQLRepository",
    "MarketSnapshotPostgreSQLRepository",
    "MarketSnapshotMemoryRepository",
    "NotificationMemoryRepository",
    "NotificationPostgreSQLRepository",
    "OpportunityDetailPostgreSQLRepository",
    "OpportunityDetailMemoryRepository",
    "OpportunityMemoryRepository",
    "OpportunityPlanPostgreSQLRepository",
    "OpportunityPlanMemoryRepository",
    "OpportunityPostgreSQLRepository",
    "PostgreSQLImmutableRepository",
    "QualificationPostgreSQLRepository",
    "QualificationMemoryRepository",
    "RankingMemoryRepository",
    "RankingPostgreSQLRepository",
    "RuntimeGovernancePostgreSQLRepository",
    "RuntimeGovernanceMemoryRepository",
    "ScoringMemoryRepository",
    "ScoringPostgreSQLRepository",
)
